<?php 
/** 
* @brief 
 * @author Vinicius Goncalves Cordeiro <vinicordeirogo@gmail.com><https://github.com/vinicius-g-cordeiro>
 * @version 1.0
 * @date 2026/08/29
 * @copyright Copyright (c) 2026 - Vinicius Goncalves Cordeiro <vinicordeirogo@gmail.com> <https://github.com/vinicius-g-cordeiro>
 */

declare(strict_types=1);


namespace App\Database\Schema;

use App\Database\Attributes\Column;
use App\Database\Attributes\ForeignKeyConstraint;
use App\Database\Attributes\Index;
use App\Database\Attributes\UniqueConstraint;
use ReflectionClass;


class Schema {
    public string $table = 'example' {
        set(string $value) {
            $this->table = strtolower($value);
        }
    }

    #[Column(type: 'BIGINT', default: 'GENERATED BY DEFAULT AS IDENTITY', nullable: false, comment: '')]
    public ?int $id = 1;

    #[Column(type: 'UUID', default: 'uuidv4()', nullable: false, comment: 'Unique ID for the records on this table')]
    public ?string $uuid = '';

    #[Column(type: 'TIMESTAMP',default: 'CURRENT_TIMESTAMP', nullable: false, comment: 'Created date when the record was set on the database, should never be null')]
    public ?int $created_at = 0;

    #[Column(type: 'TIMESTAMP',default: null, nullable: true, comment: '')]
    public  ?string $updated_at = null;

    #[Column(type: 'TIMESTAMP',default: null, nullable: true, comment: '')]
    public ?string $deleted_at = null;

    #[Column(type: 'BIGINT',default: 1, nullable: false, comment: '')]
    public ?int $created_by = 1;
    #[Column(type: 'BIGINT',default: null, nullable: true, comment: '')]
    public ?int $updated_by = null;
    #[Column(type: 'BIGINT',default: null, nullable: true, comment: '')]
    public ?int $deleted_by = null;

    #[Column(type: 'BIGINT',default: 1, nullable: false, comment: 'Tenant id for multi-tenant management using RLS')]
    public ?int $tenant_id = 1;

    #[Column(type: 'BIT(1)',default: 'B\'1\'', nullable: false, comment: '')]
    public ?int $active = 1;

    /**
     * @var object
     */
    public ?object $indexes;
    public ?object $constraints;
    
    function __construct(){
        $this->indexes = new \stdClass();
        $this->constraints = new \stdClass();
    }

    public static function columns(object $object) : array {
        $reflection = new ReflectionClass($object);
        $values = [];
        $classes = [];

        while ($reflection !== false) {
            $classes[] = $reflection;
            $reflection = $reflection->getParentClass();
        }

        $classes = array_reverse($classes);
        $values = [];

        foreach($classes as $class){
            foreach ($class->getProperties() as $property) {
                $propertyName = $property->getName();

                $value = $object->{$propertyName};
                $attributes = $property->getAttributes(Column::class);

                if(isset($attributes,$attributes[0]) === false) continue;
                $column = $attributes[0]->newInstance();

                if((isset($column->inherit) && $column->inherit === false)) continue; 

                $column->name = $propertyName;
                $values[$propertyName] = object(name: $propertyName, column: $column, value: $value);
            }
        }
        return $values;
    }

    public static function constraints(object $object) : array {
        $reflection = new ReflectionClass($object);
        $values = [];

        
        foreach($reflection->getAttributes() as $attributes){
            if($attributes->getName() !== ForeignKeyConstraint::class && $attributes->getName() !== UniqueConstraint::class) continue;
            $values[] = $attributes->newInstance();
        }   

        return $values;
    }

    public static function indexes(object $object) : array {
        $reflection = new ReflectionClass($object);
        $values = [];

        
        foreach($reflection->getAttributes() as $attributes){
            if($attributes->getName() !== Index::class) continue;
            $values[] = $attributes->newInstance();
        }   

        return $values;
    }
    

    public static function get(string $name = '', object $object ) : ?object{
        $reflection = new ReflectionClass($object);
        $property = $reflection->getProperty($name);

        return object(name: $property->getName(), column: $property->getAttributes(Column::class)[0], value: $object->{$property->getName()});
    }
}