<?php 
/** 
* @brief 
 * @author Vinicius Goncalves Cordeiro <vinicordeirogo@gmail.com><https://github.com/vinicius-g-cordeiro>
 * @version 1.0
 * @date 2026/08/29
 * @copyright Copyright (c) 2026 - Vinicius Goncalves Cordeiro <vinicordeirogo@gmail.com> <https://github.com/vinicius-g-cordeiro>
 */

declare(strict_types=1);


namespace App\DTOs;

use App\Database\Schema\Column;

class DTO {
    public string $table = 'example' {
        set(string $value) {
            $this->table = strtolower($value);
        }
    }
    public ?Column $id {
        get {
            return $this->id ??= new Column(name: 'id', type: 'BIGINT',default: 'GENERATED BY DEFAULT AS IDENTITY', isNull: false, comment: '');
        }
    }
    public Column $uuid {
        get {
            return $this->uuid ??= new Column(name: 'uuid', type: 'VARCHAR(64)', default: null, isNull: false, comment: 'Unique ID for the records on this table');
        }
    }

    public Column $created_at {
        get {
            return $this->created_at ??= new Column(name: 'created_at', type: 'TIMESTAMP',default: 'CURRENT_TIMESTAMP', isNull: false, comment: 'Created date when the record was set on the database, should never be null');
        }
    }

    public  Column $updated_at {
        get {
            return $this->updated_at ??= new Column(name: 'updated_at', type: 'TIMESTAMP',default: null, isNull: true, comment: '');
        }
    }

    public  Column $deleted_at {
        get {
            return $this->deleted_at ??= new Column(name: 'deleted_at', type: 'TIMESTAMP',default: null, isNull: true, comment: '');
        }
    }

    public ?Column $created_by {
        get {
            return $this->created_by ??= new Column(name: 'created_by', type: 'BIGINT',default: 0, isNull: false, comment: '');
        }
    }
    public ?Column $updated_by {
        get {
            return $this->updated_by ??= new Column(name: 'updated_by', type: 'BIGINT',default: null, isNull: true, comment: '');
        }
    }
    public ?Column $deleted_by {
        get {
            return $this->deleted_by ??= new Column(name: 'deleted_by', type: 'BIGINT',default: null, isNull: true, comment: '');
        }
    }

    public ?Column $tenant_id {
        get {
            return $this->tenant_id ??= new Column(name: 'tenant_id', type: 'BIGINT',default: 0, isNull: false, comment: 'Tenant id for multi-tenant management using RLS');
        }
    }

    public ?Column $active {
        get {
            return $this->active ??= new Column(name: 'active', type: 'BIT(1)',default: 'B\'1\'', isNull: false, comment: '');
        }
    }

    /**
     * @var object
     */
    public ?object $indexes;
    public ?object $constraints;
    
    function __construct(){
        $this->indexes = new \stdClass();
        $this->constraints = new \stdClass();
    }
}